### ISSUE TITLE
Notification Support

### ISSUE THREAD

**Issue by Abbondanzo** [Abbondanzo/peloton-reservations#5]
**Must fix**
- [x] Better copy should be displayed to signify that the user has to add their app to the home screen to allow notifications (#6)
- [x] Messenger tokens should be refreshed after notification permissions are granted (#6)
- [ ] No alerts should be displayed until permissions are granted
- [ ] Upon logging in, if permissions are not granted, the user should be forwarded to the alerts tab
- [x] Messenger tokens should be deleted when a user goes to sign out so we don't notify a device that is no longer signed in (#6)
- [x] Notifications are being received twice--we should check registration status within the service worker (#6)

**Nice to have**
- [x] App icons should not match logo but unique icon required
- [x] App title should be called "Peloton Alerts"
